name: "Publish"
on: 
  push:
    branches:
      - master

env:
  GODOT_VERSION: 4.5
  EXPORT_NAME: ${{ vars.PROJECT_NAME }}
  PROJECT_PATH: ${{ vars.PROJECT_PATH }}

jobs:
  export:
    strategy:
      matrix:
        include:
          - targetPlatform: windows
            exportName: Windows Desktop
            exportFile: $EXPORT_NAME.exe
            
          - targetPlatform: linux
            exportName: Linux
            exportFile: $EXPORT_NAME.x86_64
            
          - targetPlatform: web
            exportName: Web
            exportFile: index.html

    runs-on: ubuntu-22.04 
    name: Publish ${{ matrix.targetPlatform }} build
    
    container:
       image: barichello/godot-ci:4.5
       
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
           lfs: true
       
       - name: Setup
         run: |
           mkdir -v -p ~/.local/share/godot/export_templates/
           mkdir -v -p ~/.config/
           mv /root/.config/godot ~/.config/godot
           mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
       
       - name: ${{ matrix.exportName }} Build
         run: |
           export WINEPREFIX=/tmp/wine
           mkdir -p $WINEPREFIX
           mkdir -v -p build/${{ matrix.targetPlatform }}
           EXPORT_DIR="$(readlink -f build)"
           git config --global --add safe.directory "$GITHUB_WORKSPACE"
           cd $PROJECT_PATH
           godot --headless --verbose --export-release "${{ matrix.exportName }}" "$EXPORT_DIR/${{ matrix.targetPlatform }}/${{ matrix.exportFile }}"
       
       - name: Extract Godot project version
         id: version
         run: |
            cd $PROJECT_PATH
            VERSION=$(grep -oP 'config/version="\K[^"]+' project.godot)
            echo "Extracted version: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            
       - name: Publish on Itch
         uses: manleydev/butler-publish-itchio-action@master
         env:
           BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
           CHANNEL: ${{ matrix.targetPlatform }}
           ITCH_GAME: ${{ vars.ITCH_PROJECT }}
           ITCH_USER: ${{ vars.ITCH_USERNAME }}
           VERSION: ${{ steps.version.outputs.version }}
           PACKAGE: build/${{ matrix.targetPlatform }}